
[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "3.2.0"

[[constraint]]
  name = "github.com/go-openapi/errors"
  version = "0.19.0"

[[constraint]]
  name = "github.com/go-openapi/loads"
  version = "0.19.0"

[[constraint]]
  name = "github.com/go-openapi/runtime"
  version = "0.19.0"

[[constraint]]
  name = "github.com/go-openapi/spec"
  version = "0.19.0"

[[constraint]]
  name = "github.com/go-openapi/strfmt"
  version = "0.19.0"

[[constraint]]
  name = "github.com/go-openapi/swag"
  version = "0.19.0"

[[constraint]]
  name = "github.com/go-openapi/validate"
  version = "0.19.0"

[[constraint]]
  name = "github.com/jessevdk/go-flags"
  version = "1.4.0"

[[constraint]]
  name = "github.com/kelseyhightower/envconfig"
  version = "1.3.0"

[[constraint]]
  name = "github.com/tylerb/graceful"
  version = "1.2.15"

[[constraint]]
  name = "gopkg.in/resty.v1"
  version = "1.12.0"

[prune]
  go-tests = true
  unused-packages = true
