
[[constraint]]
  branch = "master"
  name = "github.com/go-openapi/errors"

[[constraint]]
  branch = "master"
  name = "github.com/go-openapi/loads"

[[constraint]]
  branch = "master"
  name = "github.com/go-openapi/runtime"

[[constraint]]
  branch = "master"
  name = "github.com/go-openapi/spec"

[[constraint]]
  branch = "master"
  name = "github.com/go-openapi/strfmt"

[[constraint]]
  branch = "master"
  name = "github.com/go-openapi/swag"

[[constraint]]
  branch = "master"
  name = "github.com/go-openapi/validate"

[[constraint]]
  name = "github.com/jessevdk/go-flags"
  version = "1.4.0"

[[constraint]]
  name = "github.com/kelseyhightower/envconfig"
  version = "1.3.0"

[[constraint]]
  name = "github.com/tylerb/graceful"
  version = "1.2.15"

[prune]
  go-tests = true
  unused-packages = true
