version: "2.1"

services:
  # docker-compose -f app/runtime.yml up
  api:
    image: ngc-registry-api/api:20180502
    build: .
    command: go run generated/cmd/ngc-registry-server/main.go --host 0.0.0.0 --port 9000
    ports:
      - 9000:9000
    volumes:
      - .:/go/src/github.com/pottava/ngc-registry-api/app
    working_dir: /go/src/github.com/pottava/ngc-registry-api/app
    container_name: api

  gulp:
    image: ngc-registry-api/gulp:20180502
    build: ../gulp
    volumes:
      - .:/monitor
      - /var/run/docker.sock:/var/run/docker.sock
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"
    ulimits:
      cpu:
        soft: 10
        hard: 20
    restart: always
    container_name: gulp
