version: "2.1"

services:
  # docker-compose -f app/tools.yml run --rm codegen
  codegen:
    image: supinf/go-swagger:0.18.0
    command: generate server -P lib.Principal -f spec.yaml -t app/generated
    volumes:
      - ..:/go/src/github.com/pottava/ngc-registry-api
    working_dir: /go/src/github.com/pottava/ngc-registry-api

  # docker-compose -f app/tools.yml run --rm lint
  lint:
    image: golangci/golangci-lint:v1.31.0-alpine
    command: golangci-lint run --config .golangci.yml
    volumes:
      - .:/go/src/github.com/pottava/ngc-registry-api/app
    working_dir: /go/src/github.com/pottava/ngc-registry-api/app

  # docker-compose -f app/tools.yml run --rm test
  test:
    image: ngc-registry-api/go:20200923
    build: .
    command: sh -c "go test -cover -bench -benchmem `go list ./... | grep -v /generated/` -v"
    volumes:
      - .:/go/src/github.com/pottava/ngc-registry-api/app
    working_dir: /go/src/github.com/pottava/ngc-registry-api/app

  # docker-compose -f app/tools.yml run --rm build
  build:
    image: supinf/go-gox:1.11
    command: --osarch "linux/amd64 darwin/amd64 windows/amd64" -ldflags "-s -w" -output "/go/src/github.com/pottava/ngc-registry-api/dist/{{.OS}}_{{.Arch}}"
    volumes:
      - ..:/go/src/github.com/pottava/ngc-registry-api
    working_dir: /go/src/github.com/pottava/ngc-registry-api/app/generated/cmd/ngc-registry-server
